/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SilentAlarmService } from "../silentAlarm.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SilentAlarmCreateInput } from "./SilentAlarmCreateInput";
import { SilentAlarm } from "./SilentAlarm";
import { SilentAlarmFindManyArgs } from "./SilentAlarmFindManyArgs";
import { SilentAlarmWhereUniqueInput } from "./SilentAlarmWhereUniqueInput";
import { SilentAlarmUpdateInput } from "./SilentAlarmUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SilentAlarmControllerBase {
  constructor(
    protected readonly service: SilentAlarmService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SilentAlarm })
  @nestAccessControl.UseRoles({
    resource: "SilentAlarm",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSilentAlarm(
    @common.Body() data: SilentAlarmCreateInput
  ): Promise<SilentAlarm> {
    return await this.service.createSilentAlarm({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        activationTime: true,
        createdAt: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SilentAlarm] })
  @ApiNestedQuery(SilentAlarmFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SilentAlarm",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async silentAlarms(@common.Req() request: Request): Promise<SilentAlarm[]> {
    const args = plainToClass(SilentAlarmFindManyArgs, request.query);
    return this.service.silentAlarms({
      ...args,
      select: {
        activationTime: true,
        createdAt: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SilentAlarm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SilentAlarm",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async silentAlarm(
    @common.Param() params: SilentAlarmWhereUniqueInput
  ): Promise<SilentAlarm | null> {
    const result = await this.service.silentAlarm({
      where: params,
      select: {
        activationTime: true,
        createdAt: true,
        id: true,
        location: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SilentAlarm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SilentAlarm",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSilentAlarm(
    @common.Param() params: SilentAlarmWhereUniqueInput,
    @common.Body() data: SilentAlarmUpdateInput
  ): Promise<SilentAlarm | null> {
    try {
      return await this.service.updateSilentAlarm({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          activationTime: true,
          createdAt: true,
          id: true,
          location: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SilentAlarm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SilentAlarm",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSilentAlarm(
    @common.Param() params: SilentAlarmWhereUniqueInput
  ): Promise<SilentAlarm | null> {
    try {
      return await this.service.deleteSilentAlarm({
        where: params,
        select: {
          activationTime: true,
          createdAt: true,
          id: true,
          location: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
